"""Fix attendance employee relationship

Revision ID: 6c92c8b77589
Revises: b2345377fb1c
Create Date: 2026-08-20 09:14:02.480354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c92c8b77589'
down_revision: Union[str, Sequence[str], None] = 'b2345377fb1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_employee_id'), table_name='attendance')
    op.create_index(op.f('ix_attendance_employee_id'), 'attendance', ['employee_id'], unique=False)
    op.drop_constraint(op.f('attendance_employee_id_fkey'), 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_employee_id_fkey'), 'attendance', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_attendance_employee_id'), table_name='attendance')
    op.create_index(op.f('ix_attendance_employee_id'), 'attendance', ['employee_id'], unique=True)
    # ### end Alembic commands ###
